### ISSUE TITLE
[Feature] Add custom 'starter' messages for Masks (via 'bot hello' or more detailed show/hide options for context prompts)

### ISSUE THREAD

**Issue by GOvEy1nw** [ChatGPTNextWeb/ChatGPT-Next-Web#3097]
**Is your feature request related to a problem? Please describe.**
Not related to a bug, but to the user experience.

**Describe the solution you'd like**
Hiding context prompts from chats with masks looks much cleaner, but then you're left with the default 'Hello! How can I assist you today?' initial message in the chat. It'd make for a much better UX if we could define a custom starting message (Bot Hello) for masks, so that the user can still get an idea of what the mask is intended for, without having to see all of the masks context prompts.

**Describe alternatives you've considered**
Another option would be to allow us to hide or show only specific context prompts within a masks settings, so that we can hide ones that are assigned 'user' or 'system' but show ones assigned 'assistant', or just have a toggle 'eye' button next to each context prompt that we can turn on or off to hide or show that specific context prompt.

**Comment by H0llyW00dzZ** [comment]
Interesting about show context prompts.
still on progress, can't be done quickly. since its react not a vanilla typescript

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/ab76e1ae-b1c0-49ab-bcb2-50d497905bea)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/e194f2ed-cf18-4f6e-aef3-fb94f163a44a)

**Comment by GOvEy1nw** [comment]
Awesome @H0llyW00dzZ , I don't know which way is the easier or better implementation, but one UX sample from elsewhere would be from typingmind's 'character' creation, where they have a 'welcome message' input.

<img width="750" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45126527/bbbdcf51-d7db-474b-a5ca-e962ae73431d">

The above image also demonstrates some additional features that I think would further enhance the UX in Next Web too, such as:

Character (mask) Description - so the user can see a brief explanation of what that particular mask does when selecting it from the mask list.

Profile Picture - an option to add a 'profile pic' to the mask instead of just an emoji.

Training examples - While we can already do this within Next Web via the context prompts, breaking it out into it's own 'section' in the mask creator makes it a bit more user friendly and clearer.

**Comment by H0llyW00dzZ** [comment]
- System Instruction
  it's not really needed as custom and it's way better to use this
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/b74b1fb5-f653-4aa5-944f-e31e0b3a1c61)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/07542de7-5ab4-4202-9ed5-16aa241d6211)
because if used customs it will become bad hallucinations

- Custom Welcome message 
 I'll need to figure it out later because it might require adding and migrating a new state object (local data storage) as a default.

**Comment by H0llyW00dzZ** [comment]
@GOvEy1nw 

check this : 

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/eff4ed4e-c1f8-49c1-b3a6-3b3a1c0a7c07

commits logs  : 
https://github.com/Yidadaa/ChatGPT-Next-Web/pull/3045/commits/86c0872a4f3aa981d6716756f8bf1fd0d1c33cba

note : that is way better as well
