### ISSUE TITLE
[Feature Request]: hope to add an option for a unified interface, where we can input a centralized address like one-api for redirection.

### ISSUE THREAD

**Issue by Mgrsc** [ChatGPTNextWeb/ChatGPT-Next-Web#4614]
### Problem Description

hope to add an option for a unified interface, where we can input a centralized address like one-api for redirection.

### Solution Description

Add a unified URL entry option for transit (new-api, one-api) to facilitate use after passing through intermediaries like Claude or Gemini.

**Comment by Dean-YZG** [comment]
Can you describe the usage scenario of the function and the specific problem solved?

**Comment by muaxb** [comment]
I have also encountered a similar scenario, and I will describe the specific requirements in detail: It is necessary to add a parameter to control whether the selected model must use a third-party custom interface. For example, I own a third-party proxy interface address (which includes custom features like quotas and other custom functions). This interface address has been implemented and unified all other model interfaces, such as integrating OpenAI, Claude, Gemini, etc., with the unified interface format being OpenAI's standard format. Now when I use the Claude model, I want it to go through my customized third-party proxy interface instead of calling the model's own API. Currently, I have to modify the code in api.ts to meet my needs, and the comments are the modified code.


constructor(provider: ModelProvider = ModelProvider.GPT) {
  switch (provider) {
    case ModelProvider.GeminiPro:
      this.llm = new GeminiProApi();
      break;
    case ModelProvider.Claude:
      this.llm = new ChatGPTApi();
      // this.llm = new ClaudeApi();
      break;
    default:
      this.llm = new ChatGPTApi();
  }
}



我也碰到过相关场景，我大概描述一下具体的需求：需要增加一个 参数 来控制 选用模型是否强制使用第三方自定义接口
比如我拥有一个第三方代理接口地址（里面自定义了额度等其他自定义功能），这个接口地址已经实现并统一了所有的其他模型接口，比如集成 opnenai、claude、gemini等模型，统一接口格式为openai的标准格式。
现在我调用 claude 模型，我希望走的是我自定义的第三方代理接口而不是调用本身模型相关的API，

当前情况下，我不得不修改 api.ts 里面的这段代码来实现我的需求，注释是修改过的代码

constructor(provider: ModelProvider = ModelProvider.GPT) {
  switch (provider) {
    case ModelProvider.GeminiPro:
      this.llm = new GeminiProApi();
      break;
    case ModelProvider.Claude:
      this.llm = new ChatGPTApi();
      // this.llm = new ClaudeApi();
      break;
    default:
      this.llm = new ChatGPTApi();
  }
}

**Comment by QAbot-zh** [comment]
如果能实现类似效果的话，也不失为一种解决方案：

```
  constructor(provider: ModelProvider = ModelProvider.GPT) {
    //通过环境变量选择按原始路由进行请求，还是按OpenAI的标准格式请求
    //readSomeEnvConfig() 是假想的函数
    const chatGeminiThroughOpenai = readSomeEnvConfig();
    const chatClaudeThroughOpenai = readSomeEnvConfig();
  
    switch (provider) {
      case ModelProvider.GeminiPro:
        if (chatGeminiThroughOpenai){
          this.llm = new ChatGPTApi();
        }
        else{
          this.llm = new GeminiProApi();
        }
        break;
      case ModelProvider.Claude:
        if (chatClaudeThroughOpenai){
          this.llm = new ChatGPTApi();
        }
        else{
          this.llm = new ClaudeApi();
        }
        break;
      default:
        this.llm = new ChatGPTApi();
    }
  }
```

**Comment by Mgrsc** [comment]
> Can you describe the usage scenario of the function and the specific problem solved?

正如楼下几位所说，使用场景就是经过了中转(one-api,new-api等)的api key聚合了所有模型并且请求url都是openai的url，解决了问题即通过中转服务器的url请求claude或者一些非openai url地址的模型
