### ISSUE TITLE
[Bug] 无法自动生成标题

### ISSUE THREAD

**Issue by Graysonzhan** [ChatGPTNextWeb/ChatGPT-Next-Web#5111]
### 📦 Deployment Method

Vercel

### 📌 Version

Latest

### 💻 Operating System

Windows

### 📌 System Version

Latest

### 🌐 Browser

Chrome

### 📌 Browser Version

Latest

### 🐛 Bug Description

如题，对话无法自动生成标题。

**Comment by Graysonzhan** [comment]
用的Gemini-1.5-pro

**Comment by Graysonzhan** [comment]
再次试了下，在V3.0的环境中，Gemini-1.5-Pro可以生成标题，但是在V2.14环境中，无法生成。

API用的同一个。

**Comment by EdiWang** [comment]
Same issue here with Azure Open AI. I do have `gpt-4o-mini` deployed with exact same name in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/0236e13187d396e627c1d3475653d08d75a41f4a

`CUSTOM_MODELS: -all,+gpt-4o@azure=gpt-4o,+gpt-4o-mini@azure=gpt-4o-mini`

**Comment by EdiWang** [comment]
Update:

It seems the summary request is NOT using Azure as provider, which result in 401, because the URL is incorrect.

![image](https://github.com/user-attachments/assets/5cc8bd80-7864-41ee-8577-99588dca70d3)

![image](https://github.com/user-attachments/assets/431fbb7d-14ff-43f9-b4cf-e131fff4d902)

The expected URL should be 

`/api/azure/deployments/gpt-4o-mini/chat/completions`

Actual URL is

`/api/openai/v1/chat/completions`

**Comment by Lightmani** [comment]
> Same issue here with Azure Open AI. I do have `gpt-4o-mini` deployed with exact same name in [0236e13](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/0236e13187d396e627c1d3475653d08d75a41f4a)
> 
> `CUSTOM_MODELS: -all,+gpt-4o@azure=gpt-4o,+gpt-4o-mini@azure=gpt-4o-mini`

Same As you.

**Comment by Dogtiti** [comment]
fixed

**Comment by Graysonzhan** [comment]
更新到最新版，还是Gemini Pro还是无法生成标题
