### ISSUE TITLE
[Bug] 同时填入openai和gemini的key和代理地址，貌似默认使用openai的key，此时如何切换或使用gemini的key

### ISSUE THREAD

**Issue by DreamofInfinity1** [ChatGPTNextWeb/ChatGPT-Next-Web#5492]
### 📦 部署方式

Other

### 📌 软件版本

v2.15.2

### 💻 系统环境

Windows

### 📌 系统版本

win11

### 🌐 浏览器

Edge

### 📌 浏览器版本

edge

### 🐛 问题描述

部署在cloudflare，同时填入openai和gemini的key和代理地址，貌似默认使用openai的key，此时如何切换或使用gemini的key

**Comment by H0llyW00dzZ** [comment]
> ### 📦 部署方式
> Other
> 
> ### 📌 软件版本
> v2.15.2
> 
> ### 💻 系统环境
> Windows
> 
> ### 📌 系统版本
> win11
> 
> ### 🌐 浏览器
> Edge
> 
> ### 📌 浏览器版本
> edge
> 
> ### 🐛 问题描述
> 部署在cloudflare，同时填入openai和gemini的key和代理地址，貌似默认使用openai的key，此时如何切换或使用gemini的key
> 
> ### 📷 复现步骤
> _No response_
> 
> ### 🚦 期望结果
> _No response_
> 
> ### 📝 补充信息
> _No response_

You have to go to the settings, I think. For example, like this:

![image](https://github.com/user-attachments/assets/d4d6b915-4157-425d-9814-498e47039995)

Then, go back to the chat because the old desktop version, which is built into binaries (client-side only), still works for me using this method.

**Comment by DreamofInfinity1** [comment]
@H0llyW00dzZ 我是将openai和gemini的key和代理地址以环境变量嵌入程序，我想在此种情景下进行切换

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/2b99cd8d-8175-40ac-8a37-6a2da9999068)
